### Задание 1. Парсинг таблицы (0.5 балла)

Извлеките таблицу с курсом валют с сайта Банка России https://www.cbr.ru/currency_base/daily/

Можно собирать теги таблицы через requests и BeautifulSoup циклом (сложнее) **ИЛИ** использовать pandas (удобнее, в одну строку)

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import json
import datetime
from time import sleep

In [51]:
table = pd.read_html('https://www.cbr.ru/currency_base/daily/')

df = table[0]
df.head()

   Цифр. код Букв. код  Единиц                 Валюта    Курс
0         36       AUD       1   Австралийский доллар  514324
1        944       AZN       1  Азербайджанский манат  420901
2         12       DZD     100      Алжирских динаров  537635
3         51       AMD     100       Армянских драмов  194253
4        764       THB      10                  Батов  219589

### Задание 2. Парсинг requests + BeautifulSoup (3 балла)

С главной страницы сайта: https://naked-science.ru/ извлеките новости.

1. Передайте ссылку в requests и BeautifulSoup
2. Пройдите циклом по всем тегам 'div' с атрибутами class="news-item grid" и извлеките из каждого:
    - заголовок ('h3')
    - текст превью ('p')
    - автора ('div', class="meta-item_author")
    - ссылку на новость ('a', class="animate-custom") - не забудьте, что сама ссылка хранится в атрибуте 'href', нужно ее извлечь: .get('href')
    - дату (определите тег и атрибут самостоятельно)
    - просмотры (определите тег и атрибут самостоятельно)
    - теги (определите тег и атрибут самостоятельно), их можно собрать из общего тега и предобработать: заменить '#' на пустые кавычки и разделить .split() либо использовать вложенный цикл.
3. Соберите результат в датафрейм

Пример работы вашего цикла:

```
for tag in soup.find_all('div', {'class':"news-item grid"}):
    title = tag.find('h3').text
```

In [52]:
# your code here
url = 'https://naked-science.ru/'
response = requests.get(url)
response.encoding = 'utf-8'

soup = BeautifulSoup(response.text, 'html.parser')

result = []
for tag in soup.find_all('div', {'class': 'news-item grid'}):
    tags = tag.find_all('div', {'class': 'terms-item'})
    tags_res = [i.find('a').text.replace('#', '').replace('\n', '').strip() for i in tags]
    result.append({
        'title': tag.find('h3').find('a').text,
        'preview': tag.find('p').text,
        'author': tag.find('div', {'class': 'meta-item_author'}).text.replace('\n', '').strip(),
        'link': tag.find('a', {'class': 'animate-custom'}).get('href'),
        'date': tag.find('span', {'class': 'echo_date'}).text,
        'views': tag.find('span', {'class': 'fvc-count'}).text,
        'tags': tags_res
        # 'tags': tag.find('div', {'class': 'terms-item'}).find('a').text
    })

df = pd.DataFrame(result)
df.head()

,title,preview,author,link,date,views,tags
0,Археологи нашли первое свидетельство насилия н...,"Исследователи изучилили скелет лангобардки, ко...",Игорь Байдов,https://naked-science.ru/article/archeology/pe...,"2 июня, 11:01",472,"[Археология, женщины, насилие, Средневековая Е..."
1,Древнеегипетский флакон с подводкой для глаз з...,Во время раскопок в римском лагере в Йорке (Ан...,Татьяна Зайцева,https://naked-science.ru/article/archeology/dr...,"2 июня, 10:44",635,"[Археология, археологические раскопки, Древний..."
2,"Ученые выяснили, какие звуки русского языка лю...",Возьмите два вымышленных слова: «буола» и «кик...,ПНИПУ,https://naked-science.ru/article/column/zvuki-...,"2 июня, 10:36",155,"[ПНИПУ, восприятие звуков, русский язык, филол..."
3,Сверхмассивные черные дыры назвали крупнейшим ...,В популярной литературе сверхмассивные черные ...,Александр Березин,https://naked-science.ru/article/astronomy/sve...,"2 июня, 09:52",808,"[Астрономия, астрономия, астрофизика, сверхмас..."
4,Неандертальская ДНК сделала человека уязвимее ...,"Гены, унаследованные нами от неандертальцев и ...",Максим Абдулаев,https://naked-science.ru/article/biology/neand...,"2 июня, 09:32",223,"[Биология, антропогенез, иммунитет, неандертал..."

### Задание 3. Вакансии (1.5 балла)

1. Обратитесь к API портала «Работа России» (https://trudvsem.ru/opendata/api) для поиска вакансий.
2. Используйте requests.get(), преобразуйте ответ в json (используйте параметры при запросе: в "text" передайте "Python", "limit" - извлечем 100 записей).
3. Извлеките данные из ответа API. Сохраните собранную информацию в датафрейм.

In [53]:
url = 'http://opendata.trudvsem.ru/api/v1/vacancies'
params = {
    'text': 'Python',
    'limit': 100
}
result = []

response = requests.get(url, params=params)
data = response.json()
vacancies = data['results']['vacancies']
for i in vacancies:
    vacancy = i['vacancy']
    result.append({
        'job': vacancy['job-name'],
        'region': vacancy['region']['name'],
        'company': vacancy['company']['name'],
        'salary': f'{vacancy.get('salary_min')}-{vacancy.get('salary_max')}',
        'employment': vacancy.get('employment'),
        'schedule': vacancy.get('schedule'),
        'qualification': vacancy.get('qualification')


    })
df = pd.DataFrame(result)
df.head()

,job,region,company,salary,employment,schedule,qualification
0,Программист Python,Ярославская область,"ООО ""ИНФОРМАЦИОННЫЕ ТЕХНОЛОГИИ""",80000-180000,Удалённая,Полный рабочий день,-
1,Разработчик Python,Город Москва,"ООО ""РДП.РУ""",80000-120000,NaN,Полный рабочий день,Средняя
2,Программист Python,Город Москва,"ООО НПО ""ТУРБУЛЕНТНОСТЬ-ДОН""",45000-45000,NaN,Полный рабочий день,Высокая
3,Программист Python,Город Москва,"АО ""ГРИНАТОМ""",180000-250000,Удалённая,Ненормированный рабочий день,Мидл+
4,Программист Python,Город Москва,"ООО ""НТЦ ""ВУЛКАН""",180000-200000,NaN,Полный рабочий день,Программист

### Задание 4. Землетрясения в мае 2026 (3 балла)

Работаем с API USGS Earthquake Catalog, [документация](https://earthquake.usgs.gov/fdsnws/event/1/)

URL для получения данных: https://earthquake.usgs.gov/fdsnws/event/1/query

Параметры запроса (обязательные):

- format - "geojson"
- starttime – начальная дата (YYYY-MM-DD, возьмем 1 мая 2026)
- endtime – конечная дата (YYYY-MM-DD, возьмем 31 мая 2026)
- minmagnitude – минимальная магнитуда (возьмем 4.5)

Поля (ключи), которые необходимо извлечь из каждого землетрясения:

- mag - Магнитуда
- place - Описание места
- time  - Дата и время события, позже нужно   перевести из миллисекунд в читаемый формат, пример:
```
import datetime

time_ms = 1748419123460
date_obj = datetime.datetime.fromtimestamp(time_ms / 1000)
date_str = date_obj.strftime('%Y-%m-%d')
print(date_str)  # вернет 2025-05-28
```
- felt  - количество людей, почувствовавших землетрясение
- mmi   - интенсивность (измеренная инструментально)
- sig   - интенсивность по показаниям людей
- alert - уровень оповещения (green, yellow, red или None)

**Все перечисленные выше поля извлекаются по ключу `'properties'`**

- longitude, latitude, depth - координаты и глубина (км)

**Извлекаются по ключам '`geometry'` -> `'coordinates'`**, получите список [longitude, latitude, depth]

Чтобы собрать датафрейм из json, нужно:
1. Пройти по **списку словарей, ключ `features`** (это и есть землетрясения) и для каждого извлечь все перечисленные поля.
2. Сложить данные в список словарей или список списков
3. Собрать датафрейм

In [54]:
import datetime

url = 'https://earthquake.usgs.gov/fdsnws/event/1/query'
params = {'format': 'geojson',
    'starttime': '2026-05-01',
    'endtime': '2026-05-31',
    'minmagnitude': 4.5
}

response = requests.get(url, params=params)
data = response.json()
print(data)
result = []
features = data['features']
for feature in features:
    properties = feature['properties']
    geometry = feature['geometry']['coordinates']
    date_obj = datetime.datetime.fromtimestamp(properties['time'] / 1000)
    date_str = date_obj.strftime('%Y-%m-%d')
    result.append({
        'mag': properties['mag'],
        'place': properties['place'],
        'time': date_str,
        'felt': properties['felt'],
        'mmi': properties['mmi'],
        'sig': properties['sig'],
        'alert': properties['alert'],
        'longtitude': geometry[0],
        'latitude': geometry[1],
        'depth': geometry[2]
    })
df = pd.DataFrame(result)
df.head()

{'type': 'FeatureCollection', 'metadata': {'generated': 1780398395000, 'url': 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2026-05-01&endtime=2026-05-31&minmagnitude=4.5', 'title': 'USGS Earthquakes', 'status': 200, 'api': '2.4.0', 'count': 426}, 'features': [{'type': 'Feature', 'properties': {'mag': 5, 'place': '81 km SE of Lae, Papua New Guinea', 'time': 1780181151647, 'updated': 1780183425040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spkp', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spkp&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 385, 'net': 'us', 'code': '7000spkp', 'ids': ',us7000spkp,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 61, 'dmin': 2.115, 'rms': 0.77, 'gap': 62, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 5.0 - 81 km SE of Lae, Papua New Guinea'}, 'geometry': {'type': 'Point', 'coordinates': [147.4544, -7.2968, 68.854]}, 'id': 'us7000spkp'}, {'type': 'Feature', 'properties': {'mag': 5.6, 'place': '137 km SSE of Oistins, Barbados', 'time': 1780176445699, 'updated': 1780264463050, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spkc', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spkc&format=geojson', 'felt': 22, 'cdi': 4.2, 'mmi': 3.194, 'alert': 'green', 'status': 'reviewed', 'tsunami': 0, 'sig': 492, 'net': 'us', 'code': '7000spkc', 'ids': ',us7000spkc,usauto7000spkc,', 'sources': ',us,usauto,', 'types': ',dyfi,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,', 'nst': 90, 'dmin': 1.306, 'rms': 1.19, 'gap': 34, 'magType': 'mww', 'type': 'earthquake', 'title': 'M 5.6 - 137 km SSE of Oistins, Barbados'}, 'geometry': {'type': 'Point', 'coordinates': [-59.1029, 11.9084, 35]}, 'id': 'us7000spkc'}, {'type': 'Feature', 'properties': {'mag': 4.9, 'place': '24 km NNW of Murghob, Tajikistan', 'time': 1780175759807, 'updated': 1780176921040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spkb', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spkb&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 369, 'net': 'us', 'code': '7000spkb', 'ids': ',us7000spkb,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 80, 'dmin': 1.052, 'rms': 0.94, 'gap': 78, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.9 - 24 km NNW of Murghob, Tajikistan'}, 'geometry': {'type': 'Point', 'coordinates': [73.8219, 38.3564, 131.794]}, 'id': 'us7000spkb'}, {'type': 'Feature', 'properties': {'mag': 4.5, 'place': '26 km SE of Ashoro, Japan', 'time': 1780151654372, 'updated': 1780158484040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spjc', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spjc&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 312, 'net': 'us', 'code': '7000spjc', 'ids': ',us7000spjc,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 52, 'dmin': 1.158, 'rms': 0.9, 'gap': 126, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.5 - 26 km SE of Ashoro, Japan'}, 'geometry': {'type': 'Point', 'coordinates': [143.7857, 43.0767, 116.722]}, 'id': 'us7000spjc'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': '63 km W of Catuday, Philippines', 'time': 1780150869256, 'updated': 1780152109040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spj5', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spj5&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000spj5', 'ids': ',us7000spj5,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 49, 'dmin': 6.632, 'rms': 0.68, 'gap': 103, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - 63 km W of Catuday, Philippines'}, 'geometry': {'type': 'Point', 'coordinates': [119.2212, 16.3879, 10]}, 'id': 'us7000spj5'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': '62 km SE of Pondaguitan, Philippines', 'time': 1780146909763, 'updated': 1780150917040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spit', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spit&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000spit', 'ids': ',us7000spit,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 51, 'dmin': 1.478, 'rms': 1.35, 'gap': 106, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - 62 km SE of Pondaguitan, Philippines'}, 'geometry': {'type': 'Point', 'coordinates': [126.6311, 6.018, 10]}, 'id': 'us7000spit'}, {'type': 'Feature', 'properties': {'mag': 5, 'place': '195 km NNW of Kilmia, Yemen', 'time': 1780139212334, 'updated': 1780320946040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spie', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spie&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 385, 'net': 'us', 'code': '7000spie', 'ids': ',usauto7000spie,us7000spie,', 'sources': ',usauto,us,', 'types': ',internal-moment-tensor,moment-tensor,origin,phase-data,', 'nst': 39, 'dmin': 7.2, 'rms': 0.79, 'gap': 61, 'magType': 'mww', 'type': 'earthquake', 'title': 'M 5.0 - 195 km NNW of Kilmia, Yemen'}, 'geometry': {'type': 'Point', 'coordinates': [51.7816, 13.8975, 10]}, 'id': 'us7000spie'}, {'type': 'Feature', 'properties': {'mag': 4.8, 'place': '119 km SW of Jiquilillo, Nicaragua', 'time': 1780139171345, 'updated': 1780140085040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spid', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spid&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 354, 'net': 'us', 'code': '7000spid', 'ids': ',us7000spid,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 44, 'dmin': 1.453, 'rms': 0.94, 'gap': 167, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.8 - 119 km SW of Jiquilillo, Nicaragua'}, 'geometry': {'type': 'Point', 'coordinates': [-88.2604, 12.0087, 10]}, 'id': 'us7000spid'}, {'type': 'Feature', 'properties': {'mag': 4.5, 'place': '58 km NNE of Tocopilla, Chile', 'time': 1780120127991, 'updated': 1780121675040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spha', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spha&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 312, 'net': 'us', 'code': '7000spha', 'ids': ',us7000spha,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 55, 'dmin': 0.288, 'rms': 0.72, 'gap': 125, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.5 - 58 km NNE of Tocopilla, Chile'}, 'geometry': {'type': 'Point', 'coordinates': [-69.9976, -21.5931, 48.474]}, 'id': 'us7000spha'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': '73 km ESE of Pondaguitan, Philippines', 'time': 1780120093574, 'updated': 1780125758040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sphm', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sphm&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000sphm', 'ids': ',us7000sphm,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 36, 'dmin': 1.527, 'rms': 0.81, 'gap': 108, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - 73 km ESE of Pondaguitan, Philippines'}, 'geometry': {'type': 'Point', 'coordinates': [126.802, 6.1379, 10]}, 'id': 'us7000sphm'}, {'type': 'Feature', 'properties': {'mag': 5, 'place': 'South Sandwich Islands region', 'time': 1780101494852, 'updated': 1780102901040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spgb', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spgb&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 385, 'net': 'us', 'code': '7000spgb', 'ids': ',us7000spgb,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 44, 'dmin': 24.45, 'rms': 0.55, 'gap': 97, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 5.0 - South Sandwich Islands region'}, 'geometry': {'type': 'Point', 'coordinates': [-26.3858, -59.1715, 95.738]}, 'id': 'us7000spgb'}, {'type': 'Feature', 'properties': {'mag': 4.7, 'place': '72 km N of Güiria, Venezuela', 'time': 1780101102149, 'updated': 1780104348750, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spga', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spga&format=geojson', 'felt': 2, 'cdi': 2, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 340, 'net': 'us', 'code': '7000spga', 'ids': ',us7000spga,', 'sources': ',us,', 'types': ',dyfi,origin,phase-data,', 'nst': 64, 'dmin': 3.27, 'rms': 0.76, 'gap': 40, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.7 - 72 km N of Güiria, Venezuela'}, 'geometry': {'type': 'Point', 'coordinates': [-62.2793, 11.2287, 134.269]}, 'id': 'us7000spga'}, {'type': 'Feature', 'properties': {'mag': 4.8, 'place': '116 km SSE of Lorengau, Papua New Guinea', 'time': 1780096623497, 'updated': 1780098889040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spg0', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spg0&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 354, 'net': 'us', 'code': '7000spg0', 'ids': ',us7000spg0,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 43, 'dmin': 1.003, 'rms': 0.96, 'gap': 59, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.8 - 116 km SSE of Lorengau, Papua New Guinea'}, 'geometry': {'type': 'Point', 'coordinates': [147.7323, -2.9833, 10]}, 'id': 'us7000spg0'}, {'type': 'Feature', 'properties': {'mag': 4.5, 'place': '46 km ESE of Witherlea, New Zealand', 'time': 1780095390843, 'updated': 1780110382040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spft', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spft&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 312, 'net': 'us', 'code': '7000spft', 'ids': ',us7000spft,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 40, 'dmin': 0.408, 'rms': 1.37, 'gap': 70, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.5 - 46 km ESE of Witherlea, New Zealand'}, 'geometry': {'type': 'Point', 'coordinates': [174.4175, -41.7609, 16.892]}, 'id': 'us7000spft'}, {'type': 'Feature', 'properties': {'mag': 5.2, 'place': 'central Mid-Atlantic Ridge', 'time': 1780089704016, 'updated': 1780092514040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spfj', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spfj&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 416, 'net': 'us', 'code': '7000spfj', 'ids': ',usauto7000spfj,us7000spfj,', 'sources': ',usauto,us,', 'types': ',internal-moment-tensor,origin,phase-data,', 'nst': 33, 'dmin': 9.475, 'rms': 1.04, 'gap': 94, 'magType': 'mww', 'type': 'earthquake', 'title': 'M 5.2 - central Mid-Atlantic Ridge'}, 'geometry': {'type': 'Point', 'coordinates': [-29.1814, 0.9071, 10]}, 'id': 'us7000spfj'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': 'south of the Fiji Islands', 'time': 1780073269386, 'updated': 1780074350040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spdj', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spdj&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000spdj', 'ids': ',us7000spdj,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 49, 'dmin': 4.706, 'rms': 0.88, 'gap': 78, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - south of the Fiji Islands'}, 'geometry': {'type': 'Point', 'coordinates': [179.7888, -24.9835, 499.352]}, 'id': 'us7000spdj'}, {'type': 'Feature', 'properties': {'mag': 5.2, 'place': '250 km ESE of Severo-Kuril’sk, Russia', 'time': 1780070758630, 'updated': 1780071937040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spd9', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spd9&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 416, 'net': 'us', 'code': '7000spd9', 'ids': ',us7000spd9,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 64, 'dmin': 3.258, 'rms': 0.8, 'gap': 116, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 5.2 - 250 km ESE of Severo-Kuril’sk, Russia'}, 'geometry': {'type': 'Point', 'coordinates': [159.5123, 50.0568, 10]}, 'id': 'us7000spd9'}, {'type': 'Feature', 'properties': {'mag': 4.9, 'place': '56 km NNW of Kendari, Indonesia', 'time': 1780065283967, 'updated': 1780066900040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spb8', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spb8&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 369, 'net': 'us', 'code': '7000spb8', 'ids': ',us7000spb8,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 21, 'dmin': 2.992, 'rms': 1.27, 'gap': 46, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.9 - 56 km NNW of Kendari, Indonesia'}, 'geometry': {'type': 'Point', 'coordinates': [122.3461, -3.5004, 10]}, 'id': 'us7000spb8'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': '101 km E of Shikotan, Russia', 'time': 1780061833312, 'updated': 1780063687040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000spar', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000spar&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000spar', 'ids': ',us7000spar,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 64, 'dmin': 3.881, 'rms': 0.61, 'gap': 127, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - 101 km E of Shikotan, Russia'}, 'geometry': {'type': 'Point', 'coordinates': [147.967, 43.923, 35]}, 'id': 'us7000spar'}, {'type': 'Feature', 'properties': {'mag': 4.8, 'place': '13 km NNE of Palpacachi, Peru', 'time': 1780057553648, 'updated': 1780058778040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp99', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp99&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 354, 'net': 'us', 'code': '7000sp99', 'ids': ',us7000sp99,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 83, 'dmin': 4.625, 'rms': 0.6, 'gap': 107, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.8 - 13 km NNE of Palpacachi, Peru'}, 'geometry': {'type': 'Point', 'coordinates': [-72.4559, -13.758, 99.854]}, 'id': 'us7000sp99'}, {'type': 'Feature', 'properties': {'mag': 4.7, 'place': '122 km ESE of Bitung, Indonesia', 'time': 1780049044832, 'updated': 1780075351040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp8u', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp8u&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 340, 'net': 'us', 'code': '7000sp8u', 'ids': ',us7000sp8u,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 47, 'dmin': 6.051, 'rms': 0.61, 'gap': 94, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.7 - 122 km ESE of Bitung, Indonesia'}, 'geometry': {'type': 'Point', 'coordinates': [126.1429, 1.0041, 59.378]}, 'id': 'us7000sp8u'}, {'type': 'Feature', 'properties': {'mag': 4.5, 'place': '70 km ENE of San Fernando, Peru', 'time': 1780045727514, 'updated': 1780075612040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp8n', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp8n&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 312, 'net': 'us', 'code': '7000sp8n', 'ids': ',us7000sp8n,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 23, 'dmin': 4.752, 'rms': 0.76, 'gap': 102, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.5 - 70 km ENE of San Fernando, Peru'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9355, -8.1696, 197.29]}, 'id': 'us7000sp8n'}, {'type': 'Feature', 'properties': {'mag': 4.5, 'place': '108 km NNW of Bukittinggi, Indonesia', 'time': 1780044854809, 'updated': 1780055067040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp8m', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp8m&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 312, 'net': 'us', 'code': '7000sp8m', 'ids': ',us7000sp8m,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 59, 'dmin': 2.568, 'rms': 0.85, 'gap': 43, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.5 - 108 km NNW of Bukittinggi, Indonesia'}, 'geometry': {'type': 'Point', 'coordinates': [100.052, 0.6186, 170.419]}, 'id': 'us7000sp8m'}, {'type': 'Feature', 'properties': {'mag': 4.6, 'place': '24 km NNW of Kazarman, Kyrgyzstan', 'time': 1780042511417, 'updated': 1780043733040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp8f', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp8f&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 326, 'net': 'us', 'code': '7000sp8f', 'ids': ',us7000sp8f,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 79, 'dmin': 0.38, 'rms': 0.92, 'gap': 74, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 4.6 - 24 km NNW of Kazarman, Kyrgyzstan'}, 'geometry': {'type': 'Point', 'coordinates': [73.9414, 41.6125, 10]}, 'id': 'us7000sp8f'}, {'type': 'Feature', 'properties': {'mag': 5.3, 'place': '106 km SW of Turpan, China', 'time': 1780037752924, 'updated': 1780038990040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp82', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp82&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsunami': 0, 'sig': 432, 'net': 'us', 'code': '7000sp82', 'ids': ',us7000sp82,', 'sources': ',us,', 'types': ',origin,phase-data,', 'nst': 98, 'dmin': 6.441, 'rms': 1.33, 'gap': 54, 'magType': 'mb', 'type': 'earthquake', 'title': 'M 5.3 - 106 km SW of Turpan, China'}, 'geometry': {'type': 'Point', 'coordinates': [88.3187, 42.2295, 10]}, 'id': 'us7000sp82'}, {'type': 'Feature', 'properties': {'mag': 5.1, 'place': '86 km S of Pacocha, Peru', 'time': 1780032759548, 'updated': 1780033977040, 'tz': None, 'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000sp7p', 'detail': 'https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=us7000sp7p&format=geojson', 'felt': None, 'cdi': None, 'mmi': None, 'alert': None, 'status': 'reviewed', 'tsuna

,mag,place,time,felt,mmi,sig,alert,longtitude,latitude,depth
0,5.0,"81 km SE of Lae, Papua New Guinea",2026-05-31,NaN,NaN,385,NaN,147.4544,-7.2968,68.854
1,5.6,"137 km SSE of Oistins, Barbados",2026-05-31,22.0,3.194,492,green,-59.1029,11.9084,35.000
2,4.9,"24 km NNW of Murghob, Tajikistan",2026-05-31,NaN,NaN,369,NaN,73.8219,38.3564,131.794
3,4.5,"26 km SE of Ashoro, Japan",2026-05-30,NaN,NaN,312,NaN,143.7857,43.0767,116.722
4,4.6,"63 km W of Catuday, Philippines",2026-05-30,NaN,NaN,326,NaN,119.2212,16.3879,10.000

### Задание 5. Всемирный банк (дополнительно, 2 балла)
Если нет доступа к API Всемирного банка, то:
1) Выберите любой датасет / API
2) Выделите примерную структуру (какие признаки, объем, есть ли ограничения с доступом и т.д.)
3) Ответьте на вопрос: Можно ли обучить модель (регрессия / классификация)?

API Всемирного банка (World Bank Open Data), URL для получения данных: https://api.worldbank.org/v2

Загрузите данные по выбранной стране (можно использовать код страны, например "RU" для России, "US" для США, "CN" для Китая и т.д.) за период с 2000 по 2024 год.

Соберите следующие показатели (коды индикаторов Всемирного банка):

- NY.GDP.MKTP.CD – ВВП (в долларах США)
- NY.GDP.PCAP.CD – ВВП на душу населения
- NY.GDP.MKTP.KD.ZG – Годовой рост ВВП (%)
- FP.CPI.TOTL.ZG – Инфляция (дефлятор ВВП, %)
- SL.UEM.TOTL.NE.ZS – Уровень безработицы (% от общей численности рабочей силы)
- SE.XPD.TOTL.GD.ZS – Расходы на образование (% от ВВП)
- SE.TER.ENRR – Валовой коэффициент охвата высшим образованием (%)
- SP.POP.TOTL – Общая численность населения
- SP.DYN.LE00.IN – Ожидаемая продолжительность жизни при рождении (лет)

Чтобы собрать датафрейм, нужно:
- для каждого индикатора выполнить GET-запрос к API, параметры: "format" - "json", "date" - "2000:2024"
- из ответа API извлечь значения индикатора (ключ "value") за 2000-2024 гг (ключ "date").
- объединить в один датафрейм: строки — годы, столбцы — названия индикаторов (переименуйте для удобства).

**Формат ссылки для запроса**: базовая_ссылка/код_страны/indicator/код_индикатора

Важно:
- API Всемирного банка иногда возвращает пустые значения. Для некоторых показателей данные могут быть не за все годы.
- Запросы лучше выполнять с паузой (не обязательно, но вежливо).

In [ ]:
indicators = ['NY.GDP.MKTP.CD', 'NY.GDP.PCAP.CD', 'NY.GDP.MKTP.KD.ZG', 'FP.CPI.TOTL.ZG', 'SL.UEM.TOTL.NE.ZS', 'SE.XPD.TOTL.GD.ZS', 'SE.TER.ENRR', 'SP.POP.TOTL', 'SP.DYN.LE00.IN']

# your code here